local Weapons = require(game.StarterPlayer.StarterPlayerScripts.Client.features.weapons)
local Game = require(game.StarterPlayer.StarterPlayerScripts.Client.features.game)
local Shop = require(game.StarterPlayer.StarterPlayerScripts.Client.features.shop)
local Inventory = require(game.StarterPlayer.StarterPlayerScripts.Client.shared.inventory)
local LogViewer = require(game.StarterPlayer.StarterPlayerScripts.Client.LogViewer)
local Spectator = require(game.StarterPlayer.StarterPlayerScripts.Client.features.spectator)
local MapVoting = require(game.StarterPlayer.StarterPlayerScripts.Client.features.mapvoting)
local Loadout = require(game.StarterPlayer.StarterPlayerScripts.Client.features.loadout)

Shop.init()
Weapons.init()
print("Weapons initialized")
Game.init()
Inventory.init()
LogViewer.init()
Spectator.init()
MapVoting.init()
Loadout.init()