local Weapons = require(game.StarterPlayer.StarterPlayerScripts.Client.features.weapons)
local Game = require(game.StarterPlayer.StarterPlayerScripts.Client.features.game)
local Shop = require(game.StarterPlayer.StarterPlayerScripts.Client.features.shop)
local Inventory = require(game.StarterPlayer.StarterPlayerScripts.Client.features.inventory)
local LogViewer = require(game.StarterPlayer.StarterPlayerScripts.Client.LogViewer)

Shop.init()
Weapons.init()
Game.init()
Inventory.init()
LogViewer.init()